const std = @import("std");

pub const StatusCode = u32;

// Status code constants
pub const GOOD: StatusCode = 0x00000000;
pub const UNCERTAIN: StatusCode = 0x40000000;
pub const BAD: StatusCode = 0x80000000;

pub const OpcUaError = error{
    // Uncertain status codes
    Uncertain,
    UncertainReferenceNotDeleted,
    UncertainNotAllNodesAvailable,
    UncertainReferenceOutOfServer,
    UncertainNoCommunicationLastUsableValue,
    UncertainLastUsableValue,
    UncertainSubstituteValue,
    UncertainInitialValue,
    UncertainSensorNotAccurate,
    UncertainEngineeringUnitsExceeded,
    UncertainSubnormal,
    UncertainDataSubnormal,
    UncertainDominantValueChanged,
    UncertainDependentValueChanged,
    UncertainTransducerInManual,
    UncertainSimulatedValue,
    UncertainSensorCalibration,
    UncertainConfigurationError,

    // Bad status codes - General
    BadUnexpectedError,
    BadInternalError,
    BadOutOfMemory,
    BadResourceUnavailable,
    BadCommunicationError,
    BadEncodingError,
    BadDecodingError,
    BadEncodingLimitsExceeded,
    BadRequestTooLarge,
    BadResponseTooLarge,
    BadUnknownResponse,
    BadTimeout,
    BadServiceUnsupported,
    BadShutdown,
    BadServerNotConnected,
    BadServerHalted,
    BadNothingToDo,
    BadTooManyOperations,
    BadTooManyMonitoredItems,
    BadDataTypeIdUnknown,

    // Certificate related
    BadCertificateInvalid,
    BadSecurityChecksFailed,
    BadCertificatePolicyCheckFailed,
    BadCertificateTimeInvalid,
    BadCertificateIssuerTimeInvalid,
    BadCertificateHostNameInvalid,
    BadCertificateUriInvalid,
    BadCertificateUseNotAllowed,
    BadCertificateIssuerUseNotAllowed,
    BadCertificateUntrusted,
    BadCertificateRevocationUnknown,
    BadCertificateIssuerRevocationUnknown,
    BadCertificateRevoked,
    BadCertificateIssuerRevoked,
    BadCertificateChainIncomplete,

    // User/Identity related
    BadUserAccessDenied,
    BadIdentityTokenInvalid,
    BadIdentityTokenRejected,
    BadSecureChannelIdInvalid,
    BadInvalidTimestamp,
    BadNonceInvalid,
    BadSessionIdInvalid,
    BadSessionClosed,
    BadSessionNotActivated,
    BadSubscriptionIdInvalid,
    BadRequestHeaderInvalid,
    BadTimestampsToReturnInvalid,
    BadRequestCancelledByClient,
    BadTooManyArguments,

    // License related
    BadLicenseExpired,
    BadLicenseLimitsExceeded,
    BadLicenseNotAvailable,

    // Communication related
    BadNoCommunication,
    BadWaitingForInitialData,

    // Node related
    BadNodeIdInvalid,
    BadNodeIdUnknown,
    BadAttributeIdInvalid,
    BadIndexRangeInvalid,
    BadIndexRangeNoData,
    BadDataEncodingInvalid,
    BadDataEncodingUnsupported,
    BadNotReadable,
    BadNotWritable,
    BadOutOfRange,
    BadNotSupported,
    BadNotFound,
    BadObjectDeleted,
    BadNotImplemented,

    // Monitoring related
    BadMonitoringModeInvalid,
    BadMonitoredItemIdInvalid,
    BadMonitoredItemFilterInvalid,
    BadMonitoredItemFilterUnsupported,
    BadFilterNotAllowed,
    BadStructureMissing,
    BadEventFilterInvalid,
    BadContentFilterInvalid,

    // Filter related
    BadFilterOperatorInvalid,
    BadFilterOperatorUnsupported,
    BadFilterOperandCountMismatch,
    BadFilterOperandInvalid,
    BadFilterElementInvalid,
    BadFilterLiteralInvalid,
    BadContinuationPointInvalid,
    BadNoContinuationPoints,

    // Browse related
    BadReferenceTypeIdInvalid,
    BadBrowseDirectionInvalid,
    BadNodeNotInView,
    BadNumericOverflow,
    BadServerUriInvalid,
    BadServerNameMissing,
    BadDiscoveryUrlMissing,
    BadSemaphoreFileMissing,

    // Security related
    BadRequestTypeInvalid,
    BadSecurityModeRejected,
    BadSecurityPolicyRejected,
    BadTooManySessions,
    BadUserSignatureInvalid,
    BadApplicationSignatureInvalid,
    BadNoValidCertificates,
    BadIdentityChangeNotSupported,
    BadRequestCancelledByRequest,

    // Node operations
    BadParentNodeIdInvalid,
    BadReferenceNotAllowed,
    BadNodeIdRejected,
    BadNodeIdExists,
    BadNodeClassInvalid,
    BadBrowseNameInvalid,
    BadBrowseNameDuplicated,
    BadNodeAttributesInvalid,
    BadTypeDefinitionInvalid,
    BadSourceNodeIdInvalid,
    BadTargetNodeIdInvalid,
    BadDuplicateReferenceNotAllowed,
    BadInvalidSelfReference,
    BadReferenceLocalOnly,
    BadNoDeleteRights,

    // View related
    BadServerIndexInvalid,
    BadViewIdUnknown,
    BadViewTimestampInvalid,
    BadViewParameterMismatch,
    BadViewVersionInvalid,
    BadNotTypeDefinition,
    BadTooManyMatches,
    BadQueryTooComplex,
    BadNoMatch,
    BadMaxAgeInvalid,
    BadSecurityModeInsufficient,

    // History related
    BadHistoryOperationInvalid,
    BadHistoryOperationUnsupported,
    BadInvalidTimestampArgument,
    BadWriteNotSupported,
    BadTypeMismatch,
    BadMethodInvalid,
    BadArgumentsMissing,
    BadNotExecutable,

    // Subscription related
    BadTooManySubscriptions,
    BadTooManyPublishRequests,
    BadNoSubscription,
    BadSequenceNumberUnknown,
    BadMessageNotAvailable,
    BadInsufficientClientProfile,
    BadStateNotActive,
    BadAlreadyExists,

    // TCP related
    BadTcpServerTooBusy,
    BadTcpMessageTypeInvalid,
    BadTcpSecureChannelUnknown,
    BadTcpMessageTooLarge,
    BadTcpNotEnoughResources,
    BadTcpInternalError,
    BadTcpEndpointUrlInvalid,
    BadRequestInterrupted,
    BadRequestTimeout,
    BadSecureChannelClosed,
    BadSecureChannelTokenUnknown,
    BadSequenceNumberInvalid,
    BadProtocolVersionUnsupported,

    // Device/Sensor related
    BadConfigurationError,
    BadNotConnected,
    BadDeviceFailure,
    BadSensorFailure,
    BadOutOfService,
    BadDeadbandFilterInvalid,

    // Condition related
    BadRefreshInProgress,
    BadConditionAlreadyDisabled,
    BadConditionAlreadyEnabled,
    BadConditionDisabled,
    BadEventIdUnknown,
    BadEventNotAcknowledgeable,
    BadDialogNotActive,
    BadDialogResponseInvalid,
    BadConditionBranchAlreadyAcked,
    BadConditionBranchAlreadyConfirmed,
    BadConditionAlreadyShelved,
    BadConditionNotShelved,
    BadShelvingTimeOutOfRange,

    // Data related
    BadNoData,
    BadBoundNotFound,
    BadBoundNotSupported,
    BadDataLost,
    BadDataUnavailable,
    BadEntryExists,
    BadNoEntryExists,
    BadTimestampNotSupported,

    // Aggregate related
    BadAggregateListMismatch,
    BadAggregateNotSupported,
    BadAggregateInvalidInputs,
    BadAggregateConfigurationRejected,

    // Request related
    BadRequestNotAllowed,
    BadRequestNotComplete,
    BadTransactionPending,
    BadTicketRequired,
    BadTicketInvalid,
    BadLocked,

    // Value change related
    BadDominantValueChanged,
    BadDependentValueChanged,
    BadEditedOutOfRange,
    BadInitialValueOutOfRange,
    BadOutOfRangeDominantValueChanged,
    BadEditedOutOfRangeDominantValueChanged,
    BadOutOfRangeDominantValueChangedDependentValueChanged,
    BadEditedOutOfRangeDominantValueChangedDependentValueChanged,

    // Connection related
    BadInvalidArgument,
    BadConnectionRejected,
    BadDisconnect,
    BadConnectionClosed,
    BadInvalidState,
    BadEndOfStream,
    BadNoDataAvailable,
    BadWaitingForResponse,
    BadOperationAbandoned,
    BadExpectedStreamToBlock,
    BadWouldBlock,
    BadSyntaxError,
    BadMaxConnectionsReached,

    // DataSet related
    BadDataSetIdInvalid,
};

/// Convert a status code to a Zig error or void
pub fn checkStatus(status: StatusCode) OpcUaError!void {
    if (status == GOOD) return;

    // Check if it's a GOOD variant (0x00xxxxxx)
    if ((status & 0xFF000000) == 0x00000000) return;

    return switch (status) {
        // Uncertain codes
        UNCERTAIN => OpcUaError.Uncertain,
        0x40BC0000 => OpcUaError.UncertainReferenceNotDeleted,
        0x40C00000 => OpcUaError.UncertainNotAllNodesAvailable,
        0x406C0000 => OpcUaError.UncertainReferenceOutOfServer,
        0x408F0000 => OpcUaError.UncertainNoCommunicationLastUsableValue,
        0x40900000 => OpcUaError.UncertainLastUsableValue,
        0x40910000 => OpcUaError.UncertainSubstituteValue,
        0x40920000 => OpcUaError.UncertainInitialValue,
        0x40930000 => OpcUaError.UncertainSensorNotAccurate,
        0x40940000 => OpcUaError.UncertainEngineeringUnitsExceeded,
        0x40950000 => OpcUaError.UncertainSubnormal,
        0x40A40000 => OpcUaError.UncertainDataSubnormal,
        0x40DE0000 => OpcUaError.UncertainDominantValueChanged,
        0x40E20000 => OpcUaError.UncertainDependentValueChanged,
        0x42080000 => OpcUaError.UncertainTransducerInManual,
        0x42090000 => OpcUaError.UncertainSimulatedValue,
        0x420A0000 => OpcUaError.UncertainSensorCalibration,
        0x420F0000 => OpcUaError.UncertainConfigurationError,

        // Bad codes
        BAD => OpcUaError.BadUnexpectedError,
        0x80010000 => OpcUaError.BadUnexpectedError,
        0x80020000 => OpcUaError.BadInternalError,
        0x80030000 => OpcUaError.BadOutOfMemory,
        0x80040000 => OpcUaError.BadResourceUnavailable,
        0x80050000 => OpcUaError.BadCommunicationError,
        0x80060000 => OpcUaError.BadEncodingError,
        0x80070000 => OpcUaError.BadDecodingError,
        0x80080000 => OpcUaError.BadEncodingLimitsExceeded,
        0x80B80000 => OpcUaError.BadRequestTooLarge,
        0x80B90000 => OpcUaError.BadResponseTooLarge,
        0x80090000 => OpcUaError.BadUnknownResponse,
        0x800A0000 => OpcUaError.BadTimeout,
        0x800B0000 => OpcUaError.BadServiceUnsupported,
        0x800C0000 => OpcUaError.BadShutdown,
        0x800D0000 => OpcUaError.BadServerNotConnected,
        0x800E0000 => OpcUaError.BadServerHalted,
        0x800F0000 => OpcUaError.BadNothingToDo,
        0x80100000 => OpcUaError.BadTooManyOperations,
        0x80DB0000 => OpcUaError.BadTooManyMonitoredItems,
        0x80110000 => OpcUaError.BadDataTypeIdUnknown,
        0x80120000 => OpcUaError.BadCertificateInvalid,
        0x80130000 => OpcUaError.BadSecurityChecksFailed,
        0x81140000 => OpcUaError.BadCertificatePolicyCheckFailed,
        0x80140000 => OpcUaError.BadCertificateTimeInvalid,
        0x80150000 => OpcUaError.BadCertificateIssuerTimeInvalid,
        0x80160000 => OpcUaError.BadCertificateHostNameInvalid,
        0x80170000 => OpcUaError.BadCertificateUriInvalid,
        0x80180000 => OpcUaError.BadCertificateUseNotAllowed,
        0x80190000 => OpcUaError.BadCertificateIssuerUseNotAllowed,
        0x801A0000 => OpcUaError.BadCertificateUntrusted,
        0x801B0000 => OpcUaError.BadCertificateRevocationUnknown,
        0x801C0000 => OpcUaError.BadCertificateIssuerRevocationUnknown,
        0x801D0000 => OpcUaError.BadCertificateRevoked,
        0x801E0000 => OpcUaError.BadCertificateIssuerRevoked,
        0x810D0000 => OpcUaError.BadCertificateChainIncomplete,
        0x801F0000 => OpcUaError.BadUserAccessDenied,
        0x80200000 => OpcUaError.BadIdentityTokenInvalid,
        0x80210000 => OpcUaError.BadIdentityTokenRejected,
        0x80220000 => OpcUaError.BadSecureChannelIdInvalid,
        0x80230000 => OpcUaError.BadInvalidTimestamp,
        0x80240000 => OpcUaError.BadNonceInvalid,
        0x80250000 => OpcUaError.BadSessionIdInvalid,
        0x80260000 => OpcUaError.BadSessionClosed,
        0x80270000 => OpcUaError.BadSessionNotActivated,
        0x80280000 => OpcUaError.BadSubscriptionIdInvalid,
        0x802A0000 => OpcUaError.BadRequestHeaderInvalid,
        0x802B0000 => OpcUaError.BadTimestampsToReturnInvalid,
        0x802C0000 => OpcUaError.BadRequestCancelledByClient,
        0x80E50000 => OpcUaError.BadTooManyArguments,
        0x810E0000 => OpcUaError.BadLicenseExpired,
        0x810F0000 => OpcUaError.BadLicenseLimitsExceeded,
        0x81100000 => OpcUaError.BadLicenseNotAvailable,
        0x80310000 => OpcUaError.BadNoCommunication,
        0x80320000 => OpcUaError.BadWaitingForInitialData,
        0x80330000 => OpcUaError.BadNodeIdInvalid,
        0x80340000 => OpcUaError.BadNodeIdUnknown,
        0x80350000 => OpcUaError.BadAttributeIdInvalid,
        0x80360000 => OpcUaError.BadIndexRangeInvalid,
        0x80370000 => OpcUaError.BadIndexRangeNoData,
        0x80380000 => OpcUaError.BadDataEncodingInvalid,
        0x80390000 => OpcUaError.BadDataEncodingUnsupported,
        0x803A0000 => OpcUaError.BadNotReadable,
        0x803B0000 => OpcUaError.BadNotWritable,
        0x803C0000 => OpcUaError.BadOutOfRange,
        0x803D0000 => OpcUaError.BadNotSupported,
        0x803E0000 => OpcUaError.BadNotFound,
        0x803F0000 => OpcUaError.BadObjectDeleted,
        0x80400000 => OpcUaError.BadNotImplemented,
        0x80410000 => OpcUaError.BadMonitoringModeInvalid,
        0x80420000 => OpcUaError.BadMonitoredItemIdInvalid,
        0x80430000 => OpcUaError.BadMonitoredItemFilterInvalid,
        0x80440000 => OpcUaError.BadMonitoredItemFilterUnsupported,
        0x80450000 => OpcUaError.BadFilterNotAllowed,
        0x80460000 => OpcUaError.BadStructureMissing,
        0x80470000 => OpcUaError.BadEventFilterInvalid,
        0x80480000 => OpcUaError.BadContentFilterInvalid,
        0x80C10000 => OpcUaError.BadFilterOperatorInvalid,
        0x80C20000 => OpcUaError.BadFilterOperatorUnsupported,
        0x80C30000 => OpcUaError.BadFilterOperandCountMismatch,
        0x80490000 => OpcUaError.BadFilterOperandInvalid,
        0x80C40000 => OpcUaError.BadFilterElementInvalid,
        0x80C50000 => OpcUaError.BadFilterLiteralInvalid,
        0x804A0000 => OpcUaError.BadContinuationPointInvalid,
        0x804B0000 => OpcUaError.BadNoContinuationPoints,
        0x804C0000 => OpcUaError.BadReferenceTypeIdInvalid,
        0x804D0000 => OpcUaError.BadBrowseDirectionInvalid,
        0x804E0000 => OpcUaError.BadNodeNotInView,
        0x81120000 => OpcUaError.BadNumericOverflow,
        0x804F0000 => OpcUaError.BadServerUriInvalid,
        0x80500000 => OpcUaError.BadServerNameMissing,
        0x80510000 => OpcUaError.BadDiscoveryUrlMissing,
        0x80520000 => OpcUaError.BadSemaphoreFileMissing,
        0x80530000 => OpcUaError.BadRequestTypeInvalid,
        0x80540000 => OpcUaError.BadSecurityModeRejected,
        0x80550000 => OpcUaError.BadSecurityPolicyRejected,
        0x80560000 => OpcUaError.BadTooManySessions,
        0x80570000 => OpcUaError.BadUserSignatureInvalid,
        0x80580000 => OpcUaError.BadApplicationSignatureInvalid,
        0x80590000 => OpcUaError.BadNoValidCertificates,
        0x80C60000 => OpcUaError.BadIdentityChangeNotSupported,
        0x805A0000 => OpcUaError.BadRequestCancelledByRequest,
        0x805B0000 => OpcUaError.BadParentNodeIdInvalid,
        0x805C0000 => OpcUaError.BadReferenceNotAllowed,
        0x805D0000 => OpcUaError.BadNodeIdRejected,
        0x805E0000 => OpcUaError.BadNodeIdExists,
        0x805F0000 => OpcUaError.BadNodeClassInvalid,
        0x80600000 => OpcUaError.BadBrowseNameInvalid,
        0x80610000 => OpcUaError.BadBrowseNameDuplicated,
        0x80620000 => OpcUaError.BadNodeAttributesInvalid,
        0x80630000 => OpcUaError.BadTypeDefinitionInvalid,
        0x80640000 => OpcUaError.BadSourceNodeIdInvalid,
        0x80650000 => OpcUaError.BadTargetNodeIdInvalid,
        0x80660000 => OpcUaError.BadDuplicateReferenceNotAllowed,
        0x80670000 => OpcUaError.BadInvalidSelfReference,
        0x80680000 => OpcUaError.BadReferenceLocalOnly,
        0x80690000 => OpcUaError.BadNoDeleteRights,
        0x806A0000 => OpcUaError.BadServerIndexInvalid,
        0x806B0000 => OpcUaError.BadViewIdUnknown,
        0x80C90000 => OpcUaError.BadViewTimestampInvalid,
        0x80CA0000 => OpcUaError.BadViewParameterMismatch,
        0x80CB0000 => OpcUaError.BadViewVersionInvalid,
        0x80C80000 => OpcUaError.BadNotTypeDefinition,
        0x806D0000 => OpcUaError.BadTooManyMatches,
        0x806E0000 => OpcUaError.BadQueryTooComplex,
        0x806F0000 => OpcUaError.BadNoMatch,
        0x80700000 => OpcUaError.BadMaxAgeInvalid,
        0x80E60000 => OpcUaError.BadSecurityModeInsufficient,
        0x80710000 => OpcUaError.BadHistoryOperationInvalid,
        0x80720000 => OpcUaError.BadHistoryOperationUnsupported,
        0x80BD0000 => OpcUaError.BadInvalidTimestampArgument,
        0x80730000 => OpcUaError.BadWriteNotSupported,
        0x80740000 => OpcUaError.BadTypeMismatch,
        0x80750000 => OpcUaError.BadMethodInvalid,
        0x80760000 => OpcUaError.BadArgumentsMissing,
        0x81110000 => OpcUaError.BadNotExecutable,
        0x80770000 => OpcUaError.BadTooManySubscriptions,
        0x80780000 => OpcUaError.BadTooManyPublishRequests,
        0x80790000 => OpcUaError.BadNoSubscription,
        0x807A0000 => OpcUaError.BadSequenceNumberUnknown,
        0x807B0000 => OpcUaError.BadMessageNotAvailable,
        0x807C0000 => OpcUaError.BadInsufficientClientProfile,
        0x80BF0000 => OpcUaError.BadStateNotActive,
        0x81150000 => OpcUaError.BadAlreadyExists,
        0x807D0000 => OpcUaError.BadTcpServerTooBusy,
        0x807E0000 => OpcUaError.BadTcpMessageTypeInvalid,
        0x807F0000 => OpcUaError.BadTcpSecureChannelUnknown,
        0x80800000 => OpcUaError.BadTcpMessageTooLarge,
        0x80810000 => OpcUaError.BadTcpNotEnoughResources,
        0x80820000 => OpcUaError.BadTcpInternalError,
        0x80830000 => OpcUaError.BadTcpEndpointUrlInvalid,
        0x80840000 => OpcUaError.BadRequestInterrupted,
        0x80850000 => OpcUaError.BadRequestTimeout,
        0x80860000 => OpcUaError.BadSecureChannelClosed,
        0x80870000 => OpcUaError.BadSecureChannelTokenUnknown,
        0x80880000 => OpcUaError.BadSequenceNumberInvalid,
        0x80BE0000 => OpcUaError.BadProtocolVersionUnsupported,
        0x80890000 => OpcUaError.BadConfigurationError,
        0x808A0000 => OpcUaError.BadNotConnected,
        0x808B0000 => OpcUaError.BadDeviceFailure,
        0x808C0000 => OpcUaError.BadSensorFailure,
        0x808D0000 => OpcUaError.BadOutOfService,
        0x808E0000 => OpcUaError.BadDeadbandFilterInvalid,
        0x80970000 => OpcUaError.BadRefreshInProgress,
        0x80980000 => OpcUaError.BadConditionAlreadyDisabled,
        0x80CC0000 => OpcUaError.BadConditionAlreadyEnabled,
        0x80990000 => OpcUaError.BadConditionDisabled,
        0x809A0000 => OpcUaError.BadEventIdUnknown,
        0x80BB0000 => OpcUaError.BadEventNotAcknowledgeable,
        0x80CD0000 => OpcUaError.BadDialogNotActive,
        0x80CE0000 => OpcUaError.BadDialogResponseInvalid,
        0x80CF0000 => OpcUaError.BadConditionBranchAlreadyAcked,
        0x80D00000 => OpcUaError.BadConditionBranchAlreadyConfirmed,
        0x80D10000 => OpcUaError.BadConditionAlreadyShelved,
        0x80D20000 => OpcUaError.BadConditionNotShelved,
        0x80D30000 => OpcUaError.BadShelvingTimeOutOfRange,
        0x809B0000 => OpcUaError.BadNoData,
        0x80D70000 => OpcUaError.BadBoundNotFound,
        0x80D80000 => OpcUaError.BadBoundNotSupported,
        0x809D0000 => OpcUaError.BadDataLost,
        0x809E0000 => OpcUaError.BadDataUnavailable,
        0x809F0000 => OpcUaError.BadEntryExists,
        0x80A00000 => OpcUaError.BadNoEntryExists,
        0x80A10000 => OpcUaError.BadTimestampNotSupported,
        0x80D40000 => OpcUaError.BadAggregateListMismatch,
        0x80D50000 => OpcUaError.BadAggregateNotSupported,
        0x80D60000 => OpcUaError.BadAggregateInvalidInputs,
        0x80DA0000 => OpcUaError.BadAggregateConfigurationRejected,
        0x80E40000 => OpcUaError.BadRequestNotAllowed,
        0x81130000 => OpcUaError.BadRequestNotComplete,
        0x80E80000 => OpcUaError.BadTransactionPending,
        0x811F0000 => OpcUaError.BadTicketRequired,
        0x81200000 => OpcUaError.BadTicketInvalid,
        0x80E90000 => OpcUaError.BadLocked,
        0x80E10000 => OpcUaError.BadDominantValueChanged,
        0x80E30000 => OpcUaError.BadDependentValueChanged,
        0x81190000 => OpcUaError.BadEditedOutOfRange,
        0x811A0000 => OpcUaError.BadInitialValueOutOfRange,
        0x811B0000 => OpcUaError.BadOutOfRangeDominantValueChanged,
        0x811C0000 => OpcUaError.BadEditedOutOfRangeDominantValueChanged,
        0x811D0000 => OpcUaError.BadOutOfRangeDominantValueChangedDependentValueChanged,
        0x811E0000 => OpcUaError.BadEditedOutOfRangeDominantValueChangedDependentValueChanged,
        0x80AB0000 => OpcUaError.BadInvalidArgument,
        0x80AC0000 => OpcUaError.BadConnectionRejected,
        0x80AD0000 => OpcUaError.BadDisconnect,
        0x80AE0000 => OpcUaError.BadConnectionClosed,
        0x80AF0000 => OpcUaError.BadInvalidState,
        0x80B00000 => OpcUaError.BadEndOfStream,
        0x80B10000 => OpcUaError.BadNoDataAvailable,
        0x80B20000 => OpcUaError.BadWaitingForResponse,
        0x80B30000 => OpcUaError.BadOperationAbandoned,
        0x80B40000 => OpcUaError.BadExpectedStreamToBlock,
        0x80B50000 => OpcUaError.BadWouldBlock,
        0x80B60000 => OpcUaError.BadSyntaxError,
        0x80B70000 => OpcUaError.BadMaxConnectionsReached,
        0x80E70000 => OpcUaError.BadDataSetIdInvalid,
        else => OpcUaError.BadUnexpectedError,
    };
}

/// Check if a status code represent/// Check if a status code represents success (top 2 bits are 00)
pub fn isGood(status: StatusCode) bool {
    return (status >> 30) == 0x00;
}

/// Check if a status code represents an uncertain result (top 2 bits are 01)
pub fn isUncertain(status: StatusCode) bool {
    return (status >> 30) == 0x01;
}

/// Check if a status code represents a failure (top 2 bits are 10 or 11)
pub fn isBad(status: StatusCode) bool {
    return (status >> 30) >= 0x02;
}

/// Compare the top 16 bits of two status codes for equality
pub fn isEqualTop(s1: StatusCode, s2: StatusCode) bool {
    return (s1 & 0xFFFF0000) == (s2 & 0xFFFF0000);
}

// Example usage:
pub fn exampleFunction() !void {
    const status: StatusCode = 0x80340000; // BadNodeIdUnknown

    try checkStatus(status);
    // This will return error.BadNodeIdUnknown
}
