name: Run Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: "ci"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install zlint
        run: curl -fsSL https://raw.githubusercontent.com/DonIsaac/zlint/refs/heads/main/tasks/install.sh | bash

      - name: Run zlint
        run: zlint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.1

      - name: Install required libraries (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libmbedtls-dev libmbedx509-dev libmbedcrypto-dev

      - name: Install required libraries (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install mbedtls

      - name: Install required libraries (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mbedtls

      - name: Run unit tests
        run: |
          zig build
          zig build test --summary all

